markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Quién te financia
author: Fundación Ciudadano Inteligente
featured-image: //images/post/
url: http://www.quientefinancia.cl
description: Hasta que no sepamos quién los financia nos gobierna un poder invisible.
etiquetas: financiamiento, financiamiento campañas, financiamiento político, gasto electoral, gasto campañas, ley financiamiento electoral, transparencia electoral, transparencia campañas, limite gasto electoral, financiamiento michell bachelet, financiamiento andres velasco, financiamiento jose antonio gomez, financiamiento claudio orrego, fianciamiento andres alamand, fiananciamiento pablo longueira
twitter: ciudadanoi
github: ciudadanointeligente
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
hashtag: '#QuienTeFinancia'

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-41822715-1'
