# site settings
title: Quien te financia
email: info@ciudadanointeligente.org
description: Hasta que no sepamos qui√©n los financia nos gobierna un poder invisible.
baseurl: "http://casopenta.cl" # "http://quientefinancia.cl" ## the subpath of your site, e.g. /blog/
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-41822715-1'
basedomain: casopenta.cl #quientefinancia.cl

# build settings
markdown: kramdown
